export const FIELDS = [
  "id^3",
  "label.*^3",
  "acronym.*^3",
  "description.*^2",
  "domains.label.*",
  "publications.title.*",
  "publications.summary.*",
  "participants.structure.label.*",
  "participants.structure.acronym.*",
  "participants.structure.id",
  "call.label",
  "keywords.*",
  "action.id",
  "action.label.*",
]
export const LIGHT_SOURCE = [
  "label.*",
  "publications",
  "participants.label",
  "participants.structure.id",
  "participants.structure.label.*",
  "participants.structure.mainAddress.*",
  "year",
  "type",
  "id",
  "keywords.*",
];
