export const FIELDS = [
  "id^10",
  "externalIds.id^3",
  "title.*^3",
  "summary.*^2",
  "domains.label.*^2",
  "domains.code^2",
  "authors.fullName^2",
  "authors.denormalized.id^3",
  "authors.denormalized.orcid^3",
  "authors.denormalized.id_hal^3",
  "authors.denormalized.idref^3",
  "authors.affiliations.ids.id",
  "authors.affiliations.name",
  "source.title",
  "source.journalIssns",
  "source.publisher",
  "affiliations.id",
  "affiliations.label.*",
  "softwares.softwareName",
  "softwares.contexts",
  "softwares.wikidata",
  "projects.id",
  "projects.label.*",
  "projects.acronym.*"
]
export const LIGHT_SOURCE = ["title.*", "authors.fullName", "authors.person", "authors.role", "source.*", "isOa", 'type', 'id', "year"]
